"""empty message

Revision ID: 5b8067dc0ca7
Revises: ed7503788d26
Create Date: 2017-10-29 01:01:22.987158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8067dc0ca7'
down_revision = 'ed7503788d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'file_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_data', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
