"""empty message

Revision ID: ed7503788d26
Revises: ef37cc4d4c28
Create Date: 2017-10-28 22:29:52.299142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7503788d26'
down_revision = 'ef37cc4d4c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'file_data')
    # ### end Alembic commands ###
